test_that("Set size five dot-variables are correct", {
  expect_equal(u_const$n_subsets[5], 31)
  expect_equal(u_const$n_orders[5], 120)
  expect_equal(u_const$n_Ax[5], 75)
  expect_equal(u_const$subset_card[16], 1)
  expect_equal(u_const$subset_card[17], 2)
  expect_equal(u_const$subset_card[19], 3)
  expect_equal(u_const$subset_card[23], 4)
  expect_equal(u_const$subset_card[31], 5)
  expect_equal(u_const$subset_vectors[[31]], c(1,2,3,4,5))
  expect_equal(u_const$n_singletons[5], 5)
  expect_equal(u_const$singletons[1:5], c(1, 2, 4, 8, 16))
  expect_equal(u_const$n_doubletons[5], 10)
  expect_equal(u_const$doubletons[1:10], c(3, 5, 6, 9, 10, 12, 17, 18, 20, 24))
  expect_equal(u_const$n_tripletons[5], 10)
  expect_equal(u_const$member_table[31][1], 1)
  expect_true(is.na(u_const$member_table[30][1]))
})

test_that("create_universe() works for default object names", {
  u <- create_universe(5)
  expect_equal(u$n, 5)
  expect_equal(u$n_orders, u_const$n_orders[5])
  expect_equal(u$n_probs, u_const$n_Ax[5])
  expect_equal(u$orders[[1]], c(1,2,3,4,5))
  expect_equal(u$A_strings[31], "12345")
  expect_equal(u$order_strings[1], "12345")
})

test_that("create_universe() works for provided object names", {
  u <- create_universe(5, object_names = c("v", "w", "x", "y", "z"))
  expect_equal(u$A_strings[31], "vwxyz")
  expect_equal(u$order_strings[1], 'vwxyz')
  expect_equal(u$order_strings[120], 'zyxwv')
})
